name: CI
on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
    - 'demo/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Get Date'
        run: echo "date=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d')" >> $GITHUB_ENV

      - name: Build
        run: |
          chmod 755 ./.github/build.sh
          ./.github/build.sh
          echo "version=$(TZ=':Asia/Shanghai' date '+%Y.%m.%d')" >> ./module.prop

      - name: Build lrone
        if: ${{ startsWith(github.event.head_commit.message, '[lrone]') }}
        run: |
          chmod 755 ./.github/lrone.sh
          ./.github/lrone.sh
          echo "size=`ls -l ./themes/lrone.tar.xz | awk '{print $5}'`" >> $GITHUB_ENV

      - name: Zip Folder
        run: |
          chmod 755 ./.github/pack.sh
          ./.github/pack.sh
          zip -r MIUI_Icons-${{env.date}}.zip ./common
          zip -r MIUI_Icons-${{env.date}}.zip ./META-INF
          zip -r MIUI_Icons-${{env.date}}.zip ./icons.tar.xz
          zip -r MIUI_Icons-${{env.date}} ./module.prop
          echo "size=`ls -l ./themes/lrone.tar.xz | awk '{print $5}'`" >> $GITHUB_ENV

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ./MIUI_Icons-${{env.date}}.zip

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        if: ${{ startsWith(github.event.head_commit.message, '[lrone]') }}
        with:
          name: lrone-${{env.size}}
          path: ./themes/lrone.tar.xz

      - name: Post to channel
        if: ${{ !startsWith(github.event.head_commit.message, '[skip post]') }}
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          FILE: ./MIUI_Icons-${{env.date}}.zip
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          ESCAPED=`python3 -c 'import json,os,urllib.parse; print(urllib.parse.quote(json.dumps(os.environ["COMMIT_MESSAGE"])))'`
          curl -v "https://api.telegram.org/bot${BOT_TOKEN}/sendMediaGroup?chat_id=${CHANNEL_ID}&media=%5B%7B%22type%22:%22document%22,%20%22media%22:%22attach://release%22,%22caption%22:${ESCAPED}%7D%5D"  -F release="@$FILE"
          