name: CI
on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
    - 'demo/**'
    - 'themes/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      ! contains(github.event.head_commit.message, '[skip ci]')
      ! contains(github.event.head_commit.message, '[release]')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: |
          chmod 755 ./.github/build.sh
          ./.github/build.sh
          echo version=$(echo ${{ github.event.head_commit.id }} | head -c 8) >> $GITHUB_ENV

      - name: Zip Folder
        run: |
          echo "version=${{ env.version }}" >> ./module.prop
          echo "ver=${{ env.version }}" >> ./module.prop
          XZ_OPT=-9 tar cJf icons.tar.xz ./icons
          zip -r MIUI_Icons-${{ env.version }}.zip ./common
          zip -r MIUI_Icons-${{ env.version }}.zip ./META-INF
          zip -r MIUI_Icons-${{ env.version }}.zip ./icons.tar.xz
          zip -r MIUI_Icons-${{ env.version }}.zip ./module.prop

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ./MIUI_Icons-${{ env.version }}.zip

      - name: Post to channel
        if: ${{ !startsWith(github.event.head_commit.message, '[skip post]') }}
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          FILE: ./MIUI_Icons-${{ env.version }}.zip
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          ESCAPED=`python3 -c 'import json,os,urllib.parse; print(urllib.parse.quote(json.dumps(os.environ["COMMIT_MESSAGE"])))'`
          curl -v "https://api.telegram.org/bot${BOT_TOKEN}/sendMediaGroup?chat_id=${CHANNEL_ID}&media=%5B%7B%22type%22:%22document%22,%20%22media%22:%22attach://release%22,%22caption%22:${ESCAPED}%7D%5D"  -F release="@$FILE"
          